name: Release Drafter
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  update_release_draft:
    name: Update Release Draft

    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  build:
#    name: "Build pip package"
#    runs-on: ubuntu-latest
#    needs:
#      - generate-version
#
#    steps:
#      - name: "Checkout Action"
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - name: "Set version to pyproject.toml and __init__.py"
#        run: |
#          python scripts/set_version.py ${{ needs.generate-version.outputs.next }}
#
#      - name: Build and publish to pypi
#        uses: JRubics/poetry-publish@v2.0
#        with:
#          pypi_token: ${{ secrets.PYPI_TOKEN }}
#          python_version: "3.12"
